# Generated by Django 5.1.7 on 2025-03-08 23:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='agentexecution',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='agentexecution',
            name='duration_ms',
        ),
        migrations.RemoveField(
            model_name='agentexecution',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='agentexecution',
            name='input_text',
        ),
        migrations.RemoveField(
            model_name='agentexecution',
            name='input_tokens',
        ),
        migrations.RemoveField(
            model_name='agentexecution',
            name='output_text',
        ),
        migrations.RemoveField(
            model_name='agentexecution',
            name='output_tokens',
        ),
        migrations.RemoveField(
            model_name='agentexecution',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='agentexecution',
            name='total_tokens',
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('interview', 'Interview Agent'), ('code_review', 'Code Review Agent'), ('content_writer', 'Content Writer Agent')], default='interview', max_length=50),
        ),
        migrations.AddField(
            model_name='agent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='system_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='execution_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='input_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='output_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='tokens_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='backend.project'),
        ),
        migrations.AlterField(
            model_name='agentexecution',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='backend.agent'),
        ),
        migrations.AlterField(
            model_name='agentexecution',
            name='cost',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='agentexecution',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
